/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "jie的笔记",
  "description": "鸡鸡鸡",
  "base": "/",
  "headTags": [],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/11.png",
        "heroText": "jie",
        "bgImage": "/bj2.png",
        "bgImageStyle": {
          "height": "100%",
          "boxShadow": "0 15px 18px rgba(0,0,0,0.2)"
        },
        "heroImageStyle": {
          "maxHeight": "288px",
          "display": "block",
          "borderRadius": "19% 81% 23% 77% / 44% 57% 43% 56%",
          "boxShadow": "0 15px 18px rgba(0,0,0,0.2)"
        }
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-03c8cb46",
      "path": "/",
      "lastUpdated": "2023/4/17 16:03:20",
      "lastUpdatedTimestamp": 1681718600000
    },
    {
      "title": "Java后端学习路线",
      "frontmatter": {
        "title": "Java后端学习路线",
        "categories": [
          "后端"
        ],
        "tags": [
          "JavaScript",
          "手写"
        ],
        "sticky": 2
      },
      "regularPath": "/blogs/2.html",
      "relativePath": "blogs/2.md",
      "key": "v-42e2b751",
      "path": "/blogs/2.html",
      "headers": [
        {
          "level": 2,
          "title": "idea",
          "slug": "idea"
        }
      ],
      "lastUpdated": "2023/4/17 16:03:20",
      "lastUpdatedTimestamp": 1681718600000
    },
    {
      "title": "奥力给22",
      "frontmatter": {
        "title": "奥力给22",
        "categories": [
          "后端"
        ],
        "tags": [
          "JavaScript",
          "手写"
        ],
        "sticky": 2
      },
      "regularPath": "/blogs/3.html",
      "relativePath": "blogs/3.md",
      "key": "v-d57d241e",
      "path": "/blogs/3.html",
      "lastUpdated": "2023/4/17 16:03:20",
      "lastUpdatedTimestamp": 1681718600000
    },
    {
      "title": "手把手教你轻松手写防抖和节流🔥",
      "frontmatter": {
        "title": "手把手教你轻松手写防抖和节流🔥",
        "categories": [
          "前端"
        ],
        "tags": [
          "JavaScript",
          "手写"
        ],
        "sticky": 1
      },
      "regularPath": "/blogs/anti-shake.html",
      "relativePath": "blogs/anti-shake.md",
      "key": "v-4ca2780b",
      "path": "/blogs/anti-shake.html",
      "headers": [
        {
          "level": 2,
          "title": "起源",
          "slug": "起源"
        },
        {
          "level": 2,
          "title": "防抖",
          "slug": "防抖"
        },
        {
          "level": 2,
          "title": "节流",
          "slug": "节流"
        },
        {
          "level": 2,
          "title": "应用场景",
          "slug": "应用场景"
        },
        {
          "level": 2,
          "title": "防抖应用场景",
          "slug": "防抖应用场景"
        },
        {
          "level": 2,
          "title": "节流应用场景",
          "slug": "节流应用场景"
        },
        {
          "level": 2,
          "title": "手写防抖节流",
          "slug": "手写防抖节流"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结"
        }
      ],
      "lastUpdated": "2023/4/17 16:03:20",
      "lastUpdatedTimestamp": 1681718600000
    },
    {
      "title": "更改图标以及覆盖主题样式",
      "frontmatter": {},
      "regularPath": "/blogs/4.html",
      "relativePath": "blogs/4.md",
      "key": "v-30bfb6de",
      "path": "/blogs/4.html",
      "headers": [
        {
          "level": 2,
          "title": "使用预设图标",
          "slug": "使用预设图标"
        },
        {
          "level": 2,
          "title": "使用自己的图标",
          "slug": "使用自己的图标"
        },
        {
          "level": 2,
          "title": "覆盖主题默认样式",
          "slug": "覆盖主题默认样式"
        },
        {
          "level": 2,
          "title": "主题特征配置",
          "slug": "主题特征配置"
        }
      ],
      "lastUpdated": "2023/4/17 16:03:20",
      "lastUpdatedTimestamp": 1681718600000
    },
    {
      "title": "学习前端计划🔥",
      "frontmatter": {
        "title": "学习前端计划🔥",
        "categories": [
          "前端"
        ],
        "tags": [
          "JavaScript",
          "手写"
        ],
        "sticky": 3
      },
      "regularPath": "/blogs/plan.html",
      "relativePath": "blogs/plan.md",
      "key": "v-33f111a2",
      "path": "/blogs/plan.html",
      "headers": [
        {
          "level": 2,
          "title": "JavaScript",
          "slug": "javascript"
        },
        {
          "level": 2,
          "title": "CSS",
          "slug": "css"
        }
      ],
      "lastUpdated": "2023/4/17 16:03:20",
      "lastUpdatedTimestamp": 1681718600000
    },
    {
      "frontmatter": {
        "layout": "Tags",
        "title": "Tags"
      },
      "regularPath": "/tag/",
      "key": "v-b1564aac",
      "path": "/tag/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterKey",
        "title": "Categories"
      },
      "regularPath": "/categories/",
      "key": "v-ef9325c4",
      "path": "/categories/"
    },
    {
      "frontmatter": {
        "layout": "TimeLines",
        "title": "Timeline"
      },
      "regularPath": "/timeline/",
      "key": "v-6319eb4e",
      "path": "/timeline/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "JavaScript Tags"
      },
      "regularPath": "/tag/JavaScript/",
      "key": "v-7a5f6990",
      "path": "/tag/JavaScript/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "手写 Tags"
      },
      "regularPath": "/tag/%E6%89%8B%E5%86%99/",
      "key": "v-de8294a6",
      "path": "/tag/手写/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "后端 Categories"
      },
      "regularPath": "/categories/%E5%90%8E%E7%AB%AF/",
      "key": "v-12afc5a1",
      "path": "/categories/后端/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "前端 Categories"
      },
      "regularPath": "/categories/%E5%89%8D%E7%AB%AF/",
      "key": "v-14bbbf36",
      "path": "/categories/前端/"
    }
  ],
  "themeConfig": {
    "author": "博客",
    "lastUpdated": "更新时间",
    "subSidebar": "auto",
    "logo": "/11.png",
    "authorAvatar": "/11.png",
    "type": "blog",
    "nav": [
      {
        "text": "首页",
        "link": "/"
      },
      {
        "text": "jie的博客",
        "items": [
          {
            "text": "掘金",
            "link": "https://juejin.cn/user/4161014434105000"
          },
          {
            "text": "Github",
            "link": "https://github.com/jie0181"
          }
        ]
      }
    ],
    "blogConfig": {
      "category": {
        "location": 2,
        "text": "文章分类"
      },
      "tag": {
        "location": 4,
        "text": "标签"
      }
    }
  },
  "locales": {
    "/": {
      "lang": "zh-CN",
      "path": "/"
    }
  }
}