/**
 * Generated by "@vuepress/plugin-blog"
 */
export default {
  "tags": {
    "JavaScript": {
      "key": "JavaScript",
      "scope": "tags",
      "path": "/tag/JavaScript/",
      "pageKeys": [
        "v-42e2b751",
        "v-d57d241e",
        "v-4ca2780b",
        "v-33f111a2"
      ]
    },
    "手写": {
      "key": "手写",
      "scope": "tags",
      "path": "/tag/手写/",
      "pageKeys": [
        "v-42e2b751",
        "v-d57d241e",
        "v-4ca2780b",
        "v-33f111a2"
      ]
    }
  },
  "categories": {
    "后端": {
      "key": "后端",
      "scope": "categories",
      "path": "/categories/后端/",
      "pageKeys": [
        "v-42e2b751",
        "v-d57d241e"
      ]
    },
    "前端": {
      "key": "前端",
      "scope": "categories",
      "path": "/categories/前端/",
      "pageKeys": [
        "v-4ca2780b",
        "v-33f111a2"
      ]
    }
  },
  "timeline": {}
}